### ISSUE TITLE
spark_apply and spark_write_avro are extremely slow

### ISSUE THREAD

**Issue by oaoutpost0** [sparklyr/sparklyr#2280]
Hello, I am having trouble getting spark_apply and spark_write_avro (or spark_write_*) to run quickly. Below is some example code and the configuration I am using. This is on a 4 node yarn cluster with 31 cores each (32 total, 1 reserved). This is a sandbox cluster and nobody else is using the cluster when I am running this code.

The first time I run a spark_apply in a session, it takes a very long time (several hundred seconds) on a fairly small file (50 columns, ~6000 rows). And it doesn't even matter what the spark_apply is doing (see the below code for an example).

The second time I run spark_apply in the same session, it takes considerably less, but it still takes a long time to print the results. Worse, when I go to write out the output to avro or csv, it also takes a long time to write (2 columns, ~6000 rows). My first thought is there is a configuration problem, but I don't see what configuration could change this.

Timing problems are the same when I run this interactively via R or through `nohup Rscript file.R &`. 

Is this behavior expected (cluster overhead) or is there something going on here that needs fixed?

```r
spark_version <- "2.4.0"
suppressPackageStartupMessages({
require(sparklyr)
require(sparkavro)
require(config)
require(caret)
require(dplyr)
})

config <- get(file="spark.yml")
Sys.setenv(YARN_CONF_DIR= "yarn_conf") # this just contains the name node and resource manager urls
con <- spark_connect(config=config)

input_directory <- "hdfs://my_url.net/data/example/"
myData <- spark_read_avro(con, "sparky", input_directory)

sdf_dim(myData) # Output: [1] 6213 4176

# let's get rid of and/or rename those columns
fromVars <- c("field0", "field1") # etc, we'll subset down to 50 columns
toVars <- c("new0", "new1")

varNames <- setNames(as.list(toVars), fromVars)

myData <- myData %>%
  rename_all(toupper) %>% # goto uppercase
  select(all_of(fromVars)) %>% # subset to wanted columns
  rename_at(vars(all_of(fromVars)), ~toVars) %>% # map input names to output names
  compute()

sdf_dim(myData) # Output: [1] 6213   50

####################################
## Now for the part that takes forever
start <- proc.time()

# I could use real code below, but this doNothing takes about the same time :(
doNothing <- spark_apply(myData, function(x) {return(x)})

end <- proc.time()
print(end-start)
#  user  system elapsed
#  1.171   0.833 266.349  # ive seen this go up to 500
# but it runs pretty quickly if I try to run it again in the same session
# what gives?

####################################

# real example code below
dataTransformation <- function(df, context)
{
  mapvalues <- plyr::mapvalues
  df$new_field=mapvalues(df$old_field, c('A','B',NaN,NA,' ','" "',''), c(1,0,0,0,0,0,0),F)
  # lots more of these mappings
  
  # and operations that look like this too
  names(df)[which(names(df) == "old_field2")] <- "new_field2"
  df$new_field2 <- mapvalues(df$new_field2, c(1,2,3), c(5, 5, 6), F)
  df$new_field2 <- as.numeric(df$new_field2)

  # at the end
  scoredData <- context$score(df, context$model, context$outputNames)
  return(scoredData)
}

score <- function(df, model, outputNames)
{
  require(caret)
  
  pred = predict(model, df, type='prob')
  predDF = data.frame(PRIMARYKEY=df$PRIMARYKEY, score=pred[[1]])
  names(predDF) <- outputNames
  return(predDF)
}

model <- readRDS("/path/to/RDS")

scoredData <- myData %>% spark_apply(
                         dataTransformation,
                         context = list(model=model, score=score, 
                                        outputNames=c("PRIMARYKEY", "score")),
                         columns = list("PRIMARYKEY" = "character", "score" = "numeric")
                         ) %>%
  compute()

scoredData # run form the interactive prompt, takes a long time to print

# doesn't matter, could be spark_write_csv, still really slow, on the order of hundreds of seconds, or hours when the data is bigger
# on a 1.2 million record, 2 column attempt, I started this code in the afternoon on Friday
# it didn't finish until 10am Saturday :( :( :(
# this also likes to run out of memory every now and then
# I think i fixed the config for that, but this still takes way too long
spark_write_avro(scoredData, "hdfs://my_url.net/user/myself/output", mode="overwrite")
```

The config in spark.yml is shown below.
```yml
# Set spark options below
default:
  spark.master: yarn
  spark.submit.deployMode: client
  spark.home: /opt/spark/
  spark.yarn.jars: /opt/spark/jars/*
  spark.logConf: true

  spark.driver.memory: 2g
  spark.driver.memoryOverhead: 1024m
  spark.executor.memory: 4g
  spark.executor.memoryOverhead: 1536m
  spark.yarn.executor.memoryOverhead: 1536m
  spark.driver.maxResultSize: 64m
  spark.executor.cores: 1
  spark.yarn.stagingDir: hdfs://my_url.net:/tmp/
  spark.local.dir: /temp/
  spark.shuffle.service.enabled: true
  spark.dynamicAllocation.enabled: true

  # Fail fast for testing
  spark.yarn.maxAppAttempts: 1
  spark.task.maxFailures: 1

  spark.network.timeout: 1000
  spark.serializer: org.apache.spark.serializer.KryoSerializer

```

> utils::sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.8 (Santiago)

Matrix products: default
BLAS: /u01/R/lib/libRblas.so
LAPACK: /u01/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] dplyr_0.8.4     caret_6.0-85    ggplot2_3.2.1   lattice_0.20-38
[5] rjson_0.2.20    config_0.3      sparkavro_0.3.0 sparklyr_1.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3           lubridate_1.7.4      forge_0.2.0
 [4] class_7.3-14         assertthat_0.2.1     rprojroot_1.3-2
 [7] digest_0.6.23        ipred_0.9-9          foreach_1.4.7
[10] R6_2.4.1             plyr_1.8.5           backports_1.1.5
[13] stats4_3.5.2         httr_1.4.1           pillar_1.4.3
[16] rlang_0.4.4          lazyeval_0.2.2       rstudioapi_0.10
[19] data.table_1.12.8    rpart_4.1-13         Matrix_1.2-15
[22] splines_3.5.2        gower_0.2.1          stringr_1.4.0
[25] r2d3_0.2.3           htmlwidgets_1.5.1    munsell_0.5.0
[28] compiler_3.5.2       pkgconfig_2.0.3      askpass_1.1
[31] base64enc_0.1-3      htmltools_0.4.0      nnet_7.3-12
[34] openssl_1.4.1        tidyselect_1.0.0     tibble_2.1.3
[37] prodlim_2019.11.13   codetools_0.2-15     crayon_1.3.4
[40] dbplyr_1.4.2         withr_2.1.2          MASS_7.3-51.1
[43] recipes_0.1.9        ModelMetrics_1.2.2.1 grid_3.5.2
[46] nlme_3.1-137         jsonlite_1.6.1       gtable_0.3.0
[49] lifecycle_0.1.0      DBI_1.1.0            magrittr_1.5
[52] pROC_1.16.1          scales_1.1.0         stringi_1.4.5
[55] reshape2_1.4.3       timeDate_3043.102    ellipsis_0.3.0
[58] generics_0.0.2       vctrs_0.2.2          lava_1.6.6
[61] iterators_1.0.12     tools_3.5.2          glue_1.3.1
[64] purrr_0.3.3          survival_2.43-3      yaml_2.2.1
[67] colorspace_1.4-1
